spring.application.name=aml
spring.datasource.url=jdbc:postgresql://localhost:5432/capstone_test
spring.datasource.username=darshitdhaduk
spring.datasource.password=D@rshit123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
