spring.application.name=aml

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.expiry-ms=1800000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=darshitcoc123@gmail.com
spring.mail.password=sdcqtgtkvzjlhudl

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

